"use client"

import { motion } from "framer-motion"
import { ThumbsUp, ThumbsDown, TrendingUp, AlertTriangle, Lightbulb, Target, ChevronRight, Sparkles } from "lucide-react"
import { useState } from "react"
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { mockInsights } from "@/lib/mock-data"
import type { Insight, InsightType } from "@/lib/types"

export default function InsightsPage() {
    const [insights, setInsights] = useState(mockInsights)

    const handleFeedback = (id: string, feedback: "helpful" | "not_helpful") => {
        setInsights(prev =>
            prev.map(ins =>
                ins.id === id ? { ...ins, feedback } : ins
            )
        )
    }

    return (
        <div className="min-h-screen">
            {/* Header */}
            <header className="sticky top-0 z-30 bg-background border-b-2 border-border px-6 py-4">
                <div className="flex items-center justify-between">
                    <div>
                        <p className="font-mono text-xs text-muted-foreground uppercase tracking-wider">AI-Powered</p>
                        <h1 className="text-2xl font-black">Insights</h1>
                    </div>
                    <div className="flex items-center gap-2 bg-accent px-3 py-1 border-2 border-border">
                        <Sparkles size={14} className="text-accent-foreground" />
                        <span className="font-mono text-xs font-bold text-accent-foreground">{insights.length} NEW</span>
                    </div>
                </div>
            </header>

            <div className="p-6 space-y-4">
                {/* Insights Explanation */}
                <motion.div
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="font-mono text-xs text-muted-foreground mb-6"
                >
                    These insights are generated by AI to help you understand your money better.
                    AI never takes actions—you always stay in control.
                </motion.div>

                {/* Insight Cards */}
                {insights.map((insight, i) => (
                    <InsightCard
                        key={insight.id}
                        insight={insight}
                        delay={i * 0.1}
                        onFeedback={handleFeedback}
                    />
                ))}
            </div>
        </div>
    )
}

function InsightCard({
    insight,
    delay,
    onFeedback
}: {
    insight: Insight
    delay: number
    onFeedback: (id: string, feedback: "helpful" | "not_helpful") => void
}) {
    const [expanded, setExpanded] = useState(false)

    const typeConfig: Record<InsightType, { icon: React.ReactNode; color: string; label: string }> = {
        spending: { icon: <TrendingUp size={16} />, color: "#3b82f6", label: "Spending" },
        forecast: { icon: <TrendingUp size={16} />, color: "#22c55e", label: "Forecast" },
        anomaly: { icon: <AlertTriangle size={16} />, color: "#f59e0b", label: "Alert" },
        opportunity: { icon: <Lightbulb size={16} />, color: "#8b5cf6", label: "Opportunity" },
        goal_progress: { icon: <Target size={16} />, color: "#ec4899", label: "Goal" },
    }

    const config = typeConfig[insight.type]

    return (
        <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay }}
        >
            <Card
                className="overflow-hidden cursor-pointer"
                onClick={() => setExpanded(!expanded)}
            >
                {/* Color bar */}
                <div className="h-1" style={{ backgroundColor: config.color }} />

                <CardContent className="pt-4">
                    {/* Header */}
                    <div className="flex items-start gap-3 mb-3">
                        <div
                            className="w-8 h-8 flex items-center justify-center border-2"
                            style={{ borderColor: config.color, color: config.color }}
                        >
                            {config.icon}
                        </div>
                        <div className="flex-1">
                            <div className="flex items-center gap-2 mb-1">
                                <span
                                    className="font-mono text-[10px] uppercase tracking-wider"
                                    style={{ color: config.color }}
                                >
                                    {config.label}
                                </span>
                            </div>
                            <h3 className="font-bold text-sm">{insight.title}</h3>
                            <p className="font-mono text-xs text-muted-foreground">{insight.description}</p>
                        </div>
                        <ChevronRight
                            size={18}
                            className={`text-muted-foreground transition-transform ${expanded ? "rotate-90" : ""}`}
                        />
                    </div>

                    {/* Expanded Content */}
                    {expanded && (
                        <motion.div
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: "auto" }}
                            className="border-t-2 border-border pt-4 mt-4"
                        >
                            {/* AI Explanation */}
                            <div className="bg-muted p-4 mb-4 border-l-4" style={{ borderColor: config.color }}>
                                <p className="font-mono text-sm leading-relaxed">
                                    {insight.explanation}
                                </p>
                            </div>

                            {/* Action Button */}
                            {insight.isActionable && insight.action && (
                                <Button
                                    variant="primary"
                                    size="sm"
                                    className="w-full mb-4"
                                    onClick={(e) => {
                                        e.stopPropagation()
                                        // Handle action
                                    }}
                                >
                                    {insight.action.label}
                                </Button>
                            )}

                            {/* Feedback */}
                            <div className="flex items-center justify-between pt-2 border-t border-border">
                                <span className="font-mono text-xs text-muted-foreground">Was this helpful?</span>
                                <div className="flex gap-2">
                                    <button
                                        onClick={(e) => {
                                            e.stopPropagation()
                                            onFeedback(insight.id, "helpful")
                                        }}
                                        className={`p-2 border-2 transition-colors ${insight.feedback === "helpful"
                                                ? "bg-green-500 border-green-500 text-white"
                                                : "border-border hover:bg-muted"
                                            }`}
                                    >
                                        <ThumbsUp size={14} />
                                    </button>
                                    <button
                                        onClick={(e) => {
                                            e.stopPropagation()
                                            onFeedback(insight.id, "not_helpful")
                                        }}
                                        className={`p-2 border-2 transition-colors ${insight.feedback === "not_helpful"
                                                ? "bg-red-500 border-red-500 text-white"
                                                : "border-border hover:bg-muted"
                                            }`}
                                    >
                                        <ThumbsDown size={14} />
                                    </button>
                                </div>
                            </div>
                        </motion.div>
                    )}
                </CardContent>
            </Card>
        </motion.div>
    )
}
